config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/vowelizable.rb
concern :Vowelizable do
  def vowelize(kana_text)
    simple_vowelize(kana_text)
      .gsub(/(.ャ)/, 'ア')
      .gsub(/(.ュ)/, 'ウ')
      .gsub(/(.ョ)/, 'オ')
      .gsub(/[ア|ァ]+ァ/) { |t| t.chars.map { 'ア' }.join }
      .gsub(/[イ|ィ]+ィ/) { |t| t.chars.map { 'イ' }.join }
      .gsub(/[ウ|ゥ]+ゥ/) { |t| t.chars.map { 'ウ' }.join }
      .gsub(/[エ|ェ]+ェ/) { |t| t.chars.map { 'エ' }.join }
      .gsub(/[オ|ォ]+ォ/) { |t| t.chars.map { 'オ' }.join }
      .gsub(/[ア|イ|ウ|エ|オ][ァ|ィ|ゥ|ェ|ォ]/) { |t| (t[1].ord + 1).chr }
      .gsub(/[ア|イ|ウ|エ|オ]ー/) { |t| t[0] * 2 }
  end

  private

  def simple_vowelize(kana_text)
    kana_text.chars.map do |c|
      if c.in? %w(ア カ サ タ ナ ハ マ ヤ ラ ワ ガ ザ ダ バ パ)
        'ア'
      elsif c.in? %w(イ キ シ チ ニ ヒ ミ リ ギ ジ ヂ ビ ピ)
        'イ'
      elsif c.in? %w(ウ ク ス ツ ヌ フ ム ユ ル ヴ グ ズ ヅ ブ プ)
        'ウ'
      elsif c.in? %w(エ ケ セ テ ネ ヘ メ レ ゲ ゼ デ ベ ペ)
        'エ'
      elsif c.in? %w(オ コ ソ ト ノ ホ モ ヨ ロ ヲ ゴ ゾ ド ボ ポ)
        'オ'
      elsif c == 'ン'
        'ン'
      elsif c == 'ッ'
        'ッ'
      else
        c
      end
    end.join
  end
end

app/models/concerns/vowelizer.rb
module Vowelizer
  extend ActiveSupport::Concern

  def vowelize(kana_text)
    simple_vowelize(kana_text)
      .gsub(/(.ャ)/, 'ア')
      .gsub(/(.ュ)/, 'ウ')
      .gsub(/(.ョ)/, 'オ')
      .gsub(/[ア|ァ]+ァ/) {|text| text.chars.map { |_| 'ア' }.join }
      .gsub(/[イ|ィ]+ィ/) {|text| text.chars.map { |_| 'イ' }.join }
      .gsub(/[ウ|ゥ]+ゥ/) {|text| text.chars.map { |_| 'ウ' }.join }
      .gsub(/[エ|ェ]+ェ/) {|text| text.chars.map { |_| 'エ' }.join }
      .gsub(/[オ|ォ]+ォ/) {|text| text.chars.map { |_| 'オ' }.join }
      .gsub(/[ア|イ|ウ|エ|オ][ァ|ィ|ゥ|ェ|ォ]/) {|text| (text[1].ord + 1).chr }
      .gsub(/[ア|イ|ウ|エ|オ]ー/) {|text| text[0] * 2}
    end

  def simple_vowelize(kana_text)
    kana_text.chars.map do |c, i|
      if c.in? %w(ア カ サ タ ナ ハ マ ヤ ラ ワ ガ ザ ダ バ パ)
        'ア'
      elsif c.in? %w(イ キ シ チ ニ ヒ ミ リ ギ ジ ヂ ビ ピ)
        'イ'
      elsif c.in? %w(ウ ク ス ツ ヌ フ ム ユ ル ヴ グ ズ ヅ ブ プ)
        'ウ'
      elsif c.in? %w(エ ケ セ テ ネ ヘ メ レ ゲ ゼ デ ベ ペ)
        'エ'
      elsif c.in? %w(オ コ ソ ト ノ ホ モ ヨ ロ ヲ ゴ ゾ ド ボ ポ)
        'オ'
      elsif c == 'ン'
        'ン'
      elsif c == 'ッ'
        'ッ'
      else
        c
      end
    end.join
  end
end

app/models/indexer.rb
require 'csv'

class Indexer
  attr_accessor :client

  def initialize(keywords_file)
    @client = Elasticsearch::Persistence.client
    @keywords_file = keywords_file
  end

  def run
    mapping

    word_list.each_slice(1000) do |lines|
      docs = lines.map do |line|
        SearchableWord.new(line[1], line[0])
      end
      @client.bulk bulk_query(docs)
    end
  end

  private

    def word_list
      CSV.open(@keywords_file, col_sep: "\t")
         .select { |line| line[0].present? }
    end

    def mapping
      index = SearchableWord::INDEX

      @client.indices.delete index: index if @client.indices.exists? index: index

      settings = SearchableWord.settings.to_hash
      mappings = SearchableWord.mappings.to_hash

      @client.indices.create index: index, body: {
        settings: settings,
        mappings: mappings
      }
    end

    def bulk_query(docs)
      query = { body: [] }

      docs.flatten.each do |doc|
        header = {
          index: {
            _index: doc.class::INDEX,
            _type: doc.class::TYPE,
            _id: doc._id
          }
        }
        query[:body] << header
        query[:body] << doc.to_h
      end

      query
    end
end

app/models/message.rb
class Message < ApplicationRecord
  validates :content, presence: true

  mount_uploader :icon, IconUploader

  def make_rhymes_from_content
    split_content_into_phrases.inject([]) do |acc, phrase|
      next acc if phrase.blank?
      acc << Rhyme.new(phrase)
    end
  end

  alias_method :rhymes, :make_rhymes_from_content

  def split_content_into_phrases
    content.strip.split(/。|\.|、|,|!|！|\?|？/).map(&:strip)
  end
end

app/models/rhyme.rb
class Rhyme
  attr_reader :phrase, :number, :results
  delegate :pronunciation, :vowel, to: :text

  # number に結果の個数を指定する
  def initialize(phrase, number: 10)
    @phrase = phrase
    @number = number
    @results = convert_phrases_into_rhymes
  end

  def text
    @text ||= Text.new(phrase)
  end

  private

    def convert_phrases_into_rhymes
      length = vowel.length
      return [] if length < 3

      # 10文字から3文字まで韻踏めるか検索
      (length >= 10 ? 10 : length).downto(3).map do |n|
        SearchableWord.where(vowel[-n..-1]).response.hits.hits
      end.flatten.take(@number).sort_by { |e| [e._score, e._source.word] }
    end
end

app/models/searchable_word.rb
class SearchableWord
  include Elasticsearch::Persistence::Model
  include Vowelizable

  INDEX = 'seasrchable_words'
  TYPE = 'hatena'

  NUMBER_OF_SHARDS = 5
  NUMBER_OF_REPLICAS = 0

  index_name INDEX
  document_type TYPE

  settings number_of_shards: NUMBER_OF_SHARDS
  settings number_of_replicas: NUMBER_OF_REPLICAS

  attribute :word, String
  attribute :pronunciation, String
  attribute :vowel, String

  def initialize(word, pronunciation)
    @word = word
    @pronunciation = pronunciation
    @vowel = vowelize(pronunciation.tr('ぁ-ん', 'ァ-ン')
                                   .gsub(/ウ゛/, 'ヴ'))
  end

  class << self
    def where(vowel)
      search(size: 100, from: 1, filter: { term: { vowel: vowel } })
    end
  end
end

app/models/text.rb
class Text
  include ActiveModel::Model
  include Vowelizable

  attr_reader :vowel

  SMALL_AIUEO = %w(ァ ィ ゥ ェ ォ).freeze
  SMALL_YAYUYO = %w(ャ ュ ョ).freeze

  def initialize(text)
    @text = text
    @vowel = vowelize(pronunciation)
  end

  def pronunciation
    @pronunciation ||= parsed_text.map do |word|
      mecab_candidate = word.values.first.slice(8)
      original_word = word.keys.first
      if mecab_candidate.present?
        mecab_candidate
      elsif pronouncable?(original_word)
        original_word
      else
        original_word.chars.map { 'x' }
      end
    end.join
  end

  private

    def parsed_text
      return @parsed_text if @parsed_text.present?
      parsed_text = []
      Natto::MeCab.new
                  .parse(@text)
                  .split
                  .select { |item| item != 'EOS' }
                  .each_slice(2) do |k, v|
                    parsed_text << { k => v&.split(',') }
                  end
      @parsed_text = parsed_text
    end

    def pronouncable?(text)
      text =~ /^[\p{hiragana}|\p{katakana}|ー]+$/
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  def index
    @messages = Message.order(updated_at: :desc)
  end

  def show
  end

  def new
    @message = Message.new
  end

  def edit
  end

  def create
    @message = Message.new(message_params)

    if @message.save
      redirect_to messages_url, notice: 'Message was successfully created.'
    else
      render :new
    end
  end

  def update
    if @message.update(message_params)
      redirect_to messages_url, notice: 'Message was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @message.destroy
    redirect_to messages_url, notice: 'Message was successfully destroyed.'
  end

  private

    def set_message
      @message = Message.find(params[:id])
    end

    def message_params
      params.require(:message).permit(*%i(content created_by icon))
    end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :set_text, only: [:index]

  def index
    if @base_text.present?
      @pronunciation = @base_text.pronunciation
      @vowel = @base_text.vowel
      @results = search(@vowel)
    end
  end

  private

  def set_text
    @base_text = Text.new(params[:body]) if params[:body].present?
  end

  def search(vowel)
    length = vowel.length
    return nil if length < 3

    start = (length >= 10) ? 10 : length
    # 10文字から3文字まで韻踏めるか検索
    start.downto(3).map do |n|
      SearchableWord
        .where(vowel[(-1 * n)..-1])
        .response.hits.hits
    end.flatten.take(100)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.slim
.copyright
  | 2016 &copy; rhymechan

app/views/layouts/_header.html.slim
.header__title
  = link_to image_tag('title-logo.png', { alt: 'title-logo' }), root_path
.header__description
  | rhymechan helps u 2 konvert ill messagez in2 da dope rhyme and flow with vibez of da new $hit

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Rhymechan
    meta name="viewport" content="width=device-width, initial-scale=1"
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"
    link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32"
    link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16"
    link rel="manifest" href="/manifest.json"
    link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5"
    meta name="theme-color" content="#ffffff"
  body
    header
      = render 'layouts/header'
    main
      = yield
    footer
      = render 'layouts/footer'

app/views/messages/_form.html.slim
= form_for @message do |f|
  - if @message.errors.any?
    #error_explanation
      h2 = "#{pluralize(@message.errors.count, "error")} prohibited this message from being saved:"
      ul
        - @message.errors.full_messages.each do |message|
          li = message

  - Message.attribute_names.reject { |e| e.in?(%w(id created_at updated_at icon)) }.map(&:to_sym).each do |a|
    .field
      = f.label a
      = f.text_field a

  .field
    = f.label :icon
    = f.file_field :icon

  .actions = f.submit

app/views/messages/edit.html.slim
section
  h1 Editing message

  == render 'form'

  = link_to 'Back', messages_path

app/views/messages/index.html.slim
section.flash
  p#notice = notice

section.messages
  - @messages.each do |message|
    .message(data-id=message.id)
      .message__avatar
        = image_tag(message.icon_url) if message.icon_url
      .message__header
        .message__header-additional-data
          .message__from
            span
              = fa_icon 'heart', text: message.created_by, right: true
        .message__original
          h2 = message.content
      .message__candidates
        .loading
          .loading__spinner
          = 'Now Loading...'

section.video-wrapper
  iframe src="https://www.youtube.com/embed/XZOPiEuN7oU" frameborder="0" allowfullscreen="true"

javascript:
  $(document).on('turbolinks:load', function() {
    $('.messages').children().each(function() {
      var id = $(this).data('id');

      var jqXHR = $.ajax({
        type: 'GET',
        url: '/messages/' + id + '.json'
      });

      jqXHR.done(function(response) {
        var rhymes = response.rhymes;
        var messageCandidates = $(this).find('.message__candidates');
        $(messageCandidates).html('');

        var i = 0;

        while (i < rhymes.length) {
          var pronunciation = $('<span>').addClass('rhyme__phrase-pronunciation').html('(pronunciation: ' + rhymes[i].text.pronunciation);
          var vowel = $('<span>').addClass('rhyme__phrase-vowel').html(' vowel: ' + rhymes[i].text.vowel + ')');
          var rhymePhrase = $('<div>').addClass('rhyme__phrase').html('<i class="fa fa-comment"></i> ' + rhymes[i].phrase);
          var rhyme = $('<div>').addClass('rhyme');
          rhymePhrase.append(pronunciation);
          rhymePhrase.append(vowel);
          rhymePhrase.append(' は');
          rhyme.append(rhymePhrase);

          var candidateResultsTable = $('<table>').addClass('candidate__results__table')
          var candidateResults = $('<div>').addClass('candidate__results candidate__results--collapsed')

          var j = 0;

          while (j < rhymes[i].results.length) {
            var tr = $('<tr>');
            var tdWord = $('<td>').html(rhymes[i].results[j]._source.word);
            var tdPronunciation = $('<td>').html(rhymes[i].results[j]._source.pronunciation);
            tr.append(tdWord);
            tr.append(tdPronunciation);
            candidateResultsTable.append(tr);
            j++;
          }

          candidateResults.append(candidateResultsTable);
          rhyme.append(candidateResults);
          rhyme.append($('<p>').addClass('candidate__results__fumeru').html($('<b>').html('と踏める')))

          rhyme.on('click', function() {
            $(this).find('.candidate__results').toggleClass('candidate__results--collapsed candidate__results--expanded');
          });

          messageCandidates.append(rhyme);
          i++;
        }
      }.bind(this));
    });
  });

app/views/messages/new.html.slim
section
  h1 New message

  == render 'form'

  = link_to 'Back', messages_path